[crate_roots]
sx = "/Users/orland0x/Code/shot/sx-starknet-2/src"
alexandria_math = "/Users/orland0x/Library/Caches/com.swmansion.scarb/registry/git/checkouts/alexandria-PFJ06A11CUR5U/81bb93c/alexandria/math/src"

