[package]
name = "sx"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
allowed-libfuncs-list.name = "all"

[dependencies]
starknet = ">=2.0.1"

[scripts]
run-lib = "cairo-run src/lib.cairo"

[tool.snforge]
exit_first = true